# Configuration for FishPose model inference and evaluation

# ------------------- Device --------------------
device: 'cuda'

# ------------------- Data --------------------
data:
  root_dir: 'dataset/'
  test_json: 'annotations/test_coco.json'
  img_size: [512, 512]
  heatmap_size: [128, 128]
  output_stride: 4
  num_keypoints: 11
  sigma: 2
  
model:
  pose_head_type: 'heatmap'

  # --- Backbone Configuration ---
  backbone:
    ssm_pyramid:
      use_mamba_config: True
      mamba_config:
        in_channels: 3
        output_dims: [24, 40, 112, 320]

  # --- FPN for Feature Fusion ---
  fpn:
    out_channels: 256

  # --- Coarse Head for Initial Heatmap Generation ---
  coarse_head:
    in_channels: 256
    num_keypoints: 11

  # Fusion module for combining features
  fusion_module:
    in_channels: 256
    out_channels: 256
    num_keypoints: 11
    deformable_groups: 8

  # Pose Head for final heatmap and offset prediction
  pose_head:
    in_channels: 256
    num_keypoints: 11

  # Detection Head
  det_head:
    num_classes: 1
    in_channels: 256

# ----------------- Evaluation ----------------
evaluation:
  oks_sigmas: [0.025, 0.026, 0.026, 0.035, 0.035, 0.079, 0.079, 0.072, 0.072, 0.062, 0.062]
  batch_size: 4
  num_workers: 0
